Fixes #339 - Select All Filtered
aledi/focus pull request #341
Opened 2016-12-14 20:05 UTC by Tenorio94

2016-12-14 21:59 UTC, ecristerna requested changes

2016-12-14 21:59 UTC, ecristerna commented on src/js/liga-panel.js
> +        if (checkboxes[i].parentElement.parentElement.style.display !== 'none') {
hay qeue dejar el `checkboxes[i].className !== 'hidden'` porque estaba para los marcados en rojo (no elegibles)

2016-12-14 22:05 UTC, ecristerna commented on src/js/liga-panel.js
> +            currentChecked += checkboxes[i].checked ? 1 : -1;
si en la línea 39 estás haciendo `checkboxes[i].checked = checkedBox.checked`, que no en la línea 40 la condición siempre será `TRUE`?

2016-12-14 22:06 UTC, ecristerna commented on src/js/liga-panel.js
> +            currentChecked += checkboxes[i].checked ? 1 : -1;
ah, ya vi; que mejor sea `currentChecked += ceckBox.checked ? 1 : -1`; para no accesar a índice

2016-12-14 22:09 UTC, ecristerna commented
@Tenorio94 se me hace que no se está actualizando bien el contador. entra a un panel que ya tenga panelistas, selecciona y desselecciona todo, debería de estar en 0, y me pone los que tenía originalmente

2016-12-14 22:14 UTC, Tenorio94 commented on src/js/liga-panel.js
> +            currentChecked += checkboxes[i].checked ? 1 : -1;
Okok

2016-12-15 04:19 UTC, ecristerna approved these changes

2016-12-15 04:19 UTC, merged