Fixes #326 - Duplicar Encusta
aledi/focus pull request #361
Opened 2017-01-11 20:28 UTC by Tenorio94

2017-01-12 04:17 UTC, ecristerna requested changes

2017-01-12 04:17 UTC, ecristerna commented on src/js/encuestas.js
> +    }
no sé si entendí bien, pero creo que la primer línea `(actionText == 'agregada') ? 'preguntas.php?id=' + response.id : 'encuestas.php'`, aparte de que está de más, pues es un "unused result", ya se hace en el `switch`, no?

otra cosa, no es necesario el `break` si hay un `return` antes

2017-01-12 04:17 UTC, ecristerna commented on src/js/encuestas.js
> +            currentHTML += '<th colspan="3">Acción</th>';
hay que cambiarlo a `Acciones`, y no sé si en algún otro lado tengamos esto de que no estaba centrado…?

2017-01-12 04:17 UTC, ecristerna commented on src/js/encuestas.js
> +            return 'preguntas.php?id=' + response.id + '?parentid=' + parentIdEncuesta;
y aquí creo que el segundo parámetro es con un '&', no con un `?` o sea… `return 'preguntas.php?id=' + response.id + '&parentid=' + parentIdEncuesta;`

2017-01-12 04:17 UTC, ecristerna commented on src/js/encuestas.js
> +                myURL += '?parentid=' + result.id;
igual acá hay que cambiar el `?` por `&` si es que aplica

2017-01-12 04:17 UTC, ecristerna commented on src/js/preguntas.js
> +    if (idEncuesta.includes('parentid')) {
por lo que veo `idEncuesta` ya no es tal, sino sería mas bien `parameters`; hay que cambiarle el nombre; creo que en el otro archivo también le cambiaste algo parecido

2017-01-12 04:22 UTC, ecristerna commented on src/js/encuestas.js
> +        $('#save-encuesta').text('Duplicar');
hay que dejarlo como `Agregar`

2017-01-12 04:24 UTC, ecristerna commented on src/js/encuestas.js
> +                alert('Error editando encuesta.');
`Error agregando encuesta.`

2017-01-12 04:28 UTC, ecristerna commented on src/js/encuestas.js
>                      alert('Encuesta ' + actionText + ' exitosamente.');
Acá también hay que hacer que diga `Encuesta agregada exitosamente`, no `duplicada`. De hecho, no sé si necesitemos que la acción sea `duplicada`, para qué la usamos a parte de para cambiar textos?

2017-01-13 00:37 UTC, Tenorio94 commented on src/js/encuestas.js
> +            return 'preguntas.php?id=' + response.id + '?parentid=' + parentIdEncuesta;
Sí, ya lo corregí.

2017-01-13 00:38 UTC, Tenorio94 commented on src/js/encuestas.js
> +    }
Se me fue esa línea, la tenía nada más de referencia y olvidé borrarla. Ya corregí lo del break;

2017-01-13 00:39 UTC, Tenorio94 commented on src/js/encuestas.js
> +            currentHTML += '<th colspan="3">Acción</th>';
Aquí me di cuenta que en algún punto se cambió a colspan, que no existe como atributo. Por eso no se centraba el asunto. Pero ahorita checo dónde más se usa para arreglarlo

2017-01-13 00:40 UTC, Tenorio94 commented on src/js/encuestas.js
> +                myURL += '?parentid=' + result.id;
Este también ya lo corregí

2017-01-13 00:40 UTC, Tenorio94 commented on src/js/preguntas.js
> +    if (idEncuesta.includes('parentid')) {
Ya lo cambié como parameters.

2017-01-13 00:41 UTC, Tenorio94 commented on src/js/encuestas.js
>                      alert('Encuesta ' + actionText + ' exitosamente.');
La estoy utilizando para saber exactamente cuándo usar el parentID, no sé si te parezca o pienso en alguna otra solución. Ahorita te subo todos los cambios y me dices.

2017-01-13 00:58 UTC, ecristerna commented on src/js/encuestas.js
>                      alert('Encuesta ' + actionText + ' exitosamente.');
no, si sí se está usando, déjalo; pensé que solo era para letreros

2017-01-13 01:08 UTC, ecristerna requested changes

2017-01-13 01:08 UTC, ecristerna commented on src/js/encuestas.js
> +            currentHTML += '<th colspan="3">Acciónes</th>';
`Acciones`*

2017-01-13 01:08 UTC, ecristerna commented on src/js/encuestas.js
> +            data.parentid = parentIdEncuesta;
este `data` qué es?

2017-01-13 01:08 UTC, ecristerna commented on src/js/encuestas.js
> +        else if (parameters.substring(3) !== '' && actionText === '') {
`} else if (…`

2017-01-13 01:08 UTC, ecristerna commented on src/js/encuestas.js
> +        else {
igual acá

2017-01-13 01:08 UTC, ecristerna commented on src/js/encuestas.js
> +        var bDuplicated = false;
esta para qué es? si ya tenemos el de `actionText` que puede ser `duplicada`?

2017-01-13 01:08 UTC, ecristerna commented on src/js/preguntas.js
> +    else {
y acá

2017-01-13 01:08 UTC, ecristerna commented on src/js/preguntas.js
> +    if (idEncuesta.includes('parentid')) {
creo que no se cambió…

2017-01-14 22:36 UTC, ecristerna requested changes

2017-01-14 22:36 UTC, ecristerna commented on src/js/encuestas.js
> +            parameters.parentid = parentIdEncuesta;
para qué me mandas la llave `parentid`? yo no hago nada con eso en el backend…

2017-01-14 22:36 UTC, ecristerna commented on src/js/encuestas.js
> +            parameters.parentid = parentIdEncuesta;
aquí es donde se crea la encuesta, no? si es duplicada, es normal como si se estuviera creando, donde me mandas los parámetros base. me mandas la llave `id` cuando se está editando, que no es el caso. creo entonces que está de más, solo me deberías de mandar:

```
 var parameters = {
              action: 'ALTA_ENCUESTA',
              nombre: nombre,
              fechaInicio: fechaInicio,
              fechaFin: fechaFin,
              panel: panel
          };
```

2017-01-14 22:36 UTC, ecristerna commented on src/js/encuestas.js
> +                myURL += '?parentid=' + result.id;
este es el caso en el que no aplicaba?

2017-01-14 22:36 UTC, ecristerna commented on src/js/preguntas.js
>      var idEncuesta = window.location.search.substring(1);
qué se hace con esto, si más abajo se está volviendo a asignar algo diferente a `idEncuesta` en ambos casos del `if - else`?

2017-01-18 20:33 UTC, Tenorio94 commented on src/js/preguntas.js
>      var idEncuesta = window.location.search.substring(1);
Aquí solamente se está tomando los datos del URL para identificar si es parent. En el if - else hago el includes sobre el idEncuesta, pero si quieres puedo hacerlo directo sin guardarlo en idEncuesta, pero de todos modos tengo que ponerle algo, entonces creo que me sirve ya para no declararla vacía.

2017-01-18 20:34 UTC, Tenorio94 commented on src/js/encuestas.js
> +            parameters.parentid = parentIdEncuesta;
Ya quité el uso de parentid en ese caso. Tienes razón sobre que no se usa hehe sorry

2017-01-18 20:39 UTC, ecristerna approved these changes
Con ese último cambio y dándole una revisada antes, que funcione bien, que siga funcionando la creación y edición, etc.

2017-01-18 20:39 UTC, ecristerna commented on src/js/encuestas.js
> +            idEncuesta = '';
sugiero quitar esta asignación de aquí

2017-01-18 20:39 UTC, ecristerna commented on src/js/encuestas.js
> +            idEncuesta = '';
y de aquí

2017-01-18 20:39 UTC, ecristerna commented on src/js/encuestas.js
> +        if (idEncuesta !== '') {
y aquí, en vez de comparar `!== ''` comparar `!== 0`

2017-01-18 20:45 UTC, Tenorio94 commented on src/js/encuestas.js
> +        if (idEncuesta !== '') {
Listo

2017-01-18 21:25 UTC, merged